# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/howard/work/shadowhttp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/howard/work/shadowhttp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/shadowhttp/CMakeFiles /home/howard/work/shadowhttp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/howard/work/shadowhttp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sh-local

# Build rule for target.
sh-local: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sh-local
.PHONY : sh-local

# fast build rule for target.
sh-local/fast:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/build
.PHONY : sh-local/fast

#=============================================================================
# Target rules for targets named sh-server

# Build rule for target.
sh-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sh-server
.PHONY : sh-server

# fast build rule for target.
sh-server/fast:
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/build
.PHONY : sh-server/fast

src/core/aes256cbccodec.o: src/core/aes256cbccodec.cc.o

.PHONY : src/core/aes256cbccodec.o

# target to build an object file
src/core/aes256cbccodec.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/aes256cbccodec.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/aes256cbccodec.cc.o
.PHONY : src/core/aes256cbccodec.cc.o

src/core/aes256cbccodec.i: src/core/aes256cbccodec.cc.i

.PHONY : src/core/aes256cbccodec.i

# target to preprocess a source file
src/core/aes256cbccodec.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/aes256cbccodec.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/aes256cbccodec.cc.i
.PHONY : src/core/aes256cbccodec.cc.i

src/core/aes256cbccodec.s: src/core/aes256cbccodec.cc.s

.PHONY : src/core/aes256cbccodec.s

# target to generate assembly for a file
src/core/aes256cbccodec.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/aes256cbccodec.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/aes256cbccodec.cc.s
.PHONY : src/core/aes256cbccodec.cc.s

src/core/httpmessagecodec.o: src/core/httpmessagecodec.cc.o

.PHONY : src/core/httpmessagecodec.o

# target to build an object file
src/core/httpmessagecodec.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/httpmessagecodec.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/httpmessagecodec.cc.o
.PHONY : src/core/httpmessagecodec.cc.o

src/core/httpmessagecodec.i: src/core/httpmessagecodec.cc.i

.PHONY : src/core/httpmessagecodec.i

# target to preprocess a source file
src/core/httpmessagecodec.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/httpmessagecodec.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/httpmessagecodec.cc.i
.PHONY : src/core/httpmessagecodec.cc.i

src/core/httpmessagecodec.s: src/core/httpmessagecodec.cc.s

.PHONY : src/core/httpmessagecodec.s

# target to generate assembly for a file
src/core/httpmessagecodec.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/httpmessagecodec.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/httpmessagecodec.cc.s
.PHONY : src/core/httpmessagecodec.cc.s

src/core/padding.o: src/core/padding.cc.o

.PHONY : src/core/padding.o

# target to build an object file
src/core/padding.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/padding.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/padding.cc.o
.PHONY : src/core/padding.cc.o

src/core/padding.i: src/core/padding.cc.i

.PHONY : src/core/padding.i

# target to preprocess a source file
src/core/padding.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/padding.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/padding.cc.i
.PHONY : src/core/padding.cc.i

src/core/padding.s: src/core/padding.cc.s

.PHONY : src/core/padding.s

# target to generate assembly for a file
src/core/padding.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/padding.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/padding.cc.s
.PHONY : src/core/padding.cc.s

src/core/shadowhttpclient.o: src/core/shadowhttpclient.cc.o

.PHONY : src/core/shadowhttpclient.o

# target to build an object file
src/core/shadowhttpclient.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpclient.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpclient.cc.o
.PHONY : src/core/shadowhttpclient.cc.o

src/core/shadowhttpclient.i: src/core/shadowhttpclient.cc.i

.PHONY : src/core/shadowhttpclient.i

# target to preprocess a source file
src/core/shadowhttpclient.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpclient.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpclient.cc.i
.PHONY : src/core/shadowhttpclient.cc.i

src/core/shadowhttpclient.s: src/core/shadowhttpclient.cc.s

.PHONY : src/core/shadowhttpclient.s

# target to generate assembly for a file
src/core/shadowhttpclient.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpclient.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpclient.cc.s
.PHONY : src/core/shadowhttpclient.cc.s

src/core/shadowhttpserver.o: src/core/shadowhttpserver.cc.o

.PHONY : src/core/shadowhttpserver.o

# target to build an object file
src/core/shadowhttpserver.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpserver.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpserver.cc.o
.PHONY : src/core/shadowhttpserver.cc.o

src/core/shadowhttpserver.i: src/core/shadowhttpserver.cc.i

.PHONY : src/core/shadowhttpserver.i

# target to preprocess a source file
src/core/shadowhttpserver.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpserver.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpserver.cc.i
.PHONY : src/core/shadowhttpserver.cc.i

src/core/shadowhttpserver.s: src/core/shadowhttpserver.cc.s

.PHONY : src/core/shadowhttpserver.s

# target to generate assembly for a file
src/core/shadowhttpserver.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/core/shadowhttpserver.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/core/shadowhttpserver.cc.s
.PHONY : src/core/shadowhttpserver.cc.s

src/sh-local.o: src/sh-local.cc.o

.PHONY : src/sh-local.o

# target to build an object file
src/sh-local.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/sh-local.cc.o
.PHONY : src/sh-local.cc.o

src/sh-local.i: src/sh-local.cc.i

.PHONY : src/sh-local.i

# target to preprocess a source file
src/sh-local.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/sh-local.cc.i
.PHONY : src/sh-local.cc.i

src/sh-local.s: src/sh-local.cc.s

.PHONY : src/sh-local.s

# target to generate assembly for a file
src/sh-local.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/sh-local.cc.s
.PHONY : src/sh-local.cc.s

src/sh-server.o: src/sh-server.cc.o

.PHONY : src/sh-server.o

# target to build an object file
src/sh-server.cc.o:
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/sh-server.cc.o
.PHONY : src/sh-server.cc.o

src/sh-server.i: src/sh-server.cc.i

.PHONY : src/sh-server.i

# target to preprocess a source file
src/sh-server.cc.i:
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/sh-server.cc.i
.PHONY : src/sh-server.cc.i

src/sh-server.s: src/sh-server.cc.s

.PHONY : src/sh-server.s

# target to generate assembly for a file
src/sh-server.cc.s:
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/sh-server.cc.s
.PHONY : src/sh-server.cc.s

src/util/regextool.o: src/util/regextool.cc.o

.PHONY : src/util/regextool.o

# target to build an object file
src/util/regextool.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/regextool.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/regextool.cc.o
.PHONY : src/util/regextool.cc.o

src/util/regextool.i: src/util/regextool.cc.i

.PHONY : src/util/regextool.i

# target to preprocess a source file
src/util/regextool.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/regextool.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/regextool.cc.i
.PHONY : src/util/regextool.cc.i

src/util/regextool.s: src/util/regextool.cc.s

.PHONY : src/util/regextool.s

# target to generate assembly for a file
src/util/regextool.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/regextool.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/regextool.cc.s
.PHONY : src/util/regextool.cc.s

src/util/sockettool.o: src/util/sockettool.cc.o

.PHONY : src/util/sockettool.o

# target to build an object file
src/util/sockettool.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/sockettool.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/sockettool.cc.o
.PHONY : src/util/sockettool.cc.o

src/util/sockettool.i: src/util/sockettool.cc.i

.PHONY : src/util/sockettool.i

# target to preprocess a source file
src/util/sockettool.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/sockettool.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/sockettool.cc.i
.PHONY : src/util/sockettool.cc.i

src/util/sockettool.s: src/util/sockettool.cc.s

.PHONY : src/util/sockettool.s

# target to generate assembly for a file
src/util/sockettool.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/sockettool.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/sockettool.cc.s
.PHONY : src/util/sockettool.cc.s

src/util/stringtool.o: src/util/stringtool.cc.o

.PHONY : src/util/stringtool.o

# target to build an object file
src/util/stringtool.cc.o:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/stringtool.cc.o
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/stringtool.cc.o
.PHONY : src/util/stringtool.cc.o

src/util/stringtool.i: src/util/stringtool.cc.i

.PHONY : src/util/stringtool.i

# target to preprocess a source file
src/util/stringtool.cc.i:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/stringtool.cc.i
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/stringtool.cc.i
.PHONY : src/util/stringtool.cc.i

src/util/stringtool.s: src/util/stringtool.cc.s

.PHONY : src/util/stringtool.s

# target to generate assembly for a file
src/util/stringtool.cc.s:
	$(MAKE) -f CMakeFiles/sh-local.dir/build.make CMakeFiles/sh-local.dir/src/util/stringtool.cc.s
	$(MAKE) -f CMakeFiles/sh-server.dir/build.make CMakeFiles/sh-server.dir/src/util/stringtool.cc.s
.PHONY : src/util/stringtool.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sh-local"
	@echo "... sh-server"
	@echo "... src/core/aes256cbccodec.o"
	@echo "... src/core/aes256cbccodec.i"
	@echo "... src/core/aes256cbccodec.s"
	@echo "... src/core/httpmessagecodec.o"
	@echo "... src/core/httpmessagecodec.i"
	@echo "... src/core/httpmessagecodec.s"
	@echo "... src/core/padding.o"
	@echo "... src/core/padding.i"
	@echo "... src/core/padding.s"
	@echo "... src/core/shadowhttpclient.o"
	@echo "... src/core/shadowhttpclient.i"
	@echo "... src/core/shadowhttpclient.s"
	@echo "... src/core/shadowhttpserver.o"
	@echo "... src/core/shadowhttpserver.i"
	@echo "... src/core/shadowhttpserver.s"
	@echo "... src/sh-local.o"
	@echo "... src/sh-local.i"
	@echo "... src/sh-local.s"
	@echo "... src/sh-server.o"
	@echo "... src/sh-server.i"
	@echo "... src/sh-server.s"
	@echo "... src/util/regextool.o"
	@echo "... src/util/regextool.i"
	@echo "... src/util/regextool.s"
	@echo "... src/util/sockettool.o"
	@echo "... src/util/sockettool.i"
	@echo "... src/util/sockettool.s"
	@echo "... src/util/stringtool.o"
	@echo "... src/util/stringtool.i"
	@echo "... src/util/stringtool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

